# Generated by Django 5.2 on 2025-04-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='auteur',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
    ]
